### ISSUE TITLE
Mismatch json2csv fields&filedNames.

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportEngine#1]
https://github.com/pfitzpaddy/ngm-reportEngine/blob/c8cc51c994a0bf60e3284d1a07ebeffe557c44cb/api/controllers/Cluster/Reports/ReportController.js#L26-L101

![excel_2017-10-26_12-42-10](https://user-images.githubusercontent.com/29349472/32041910-253d0acc-ba4b-11e7-9afc-0aa5a6d75118.png)

**Comment by pfitzpaddy** [comment]
Great spot Timur, can you please make the fix. 'Facility_type_name' can be presented as 'Facilty Type'. At the same time can you please include admin3pcode and admin3name.

**Comment by pfitzpaddy** [comment]
In fact the stocks download can also have admin3pcode and admin3nam included here https://github.com/pfitzpaddy/ngm-reportEngine/blob/c8cc51c994a0bf60e3284d1a07ebeffe557c44cb/api/controllers/Cluster/Reports/ReportController.js#L138

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD
