### ISSUE TITLE
Copy Last Month error when more then one location

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportEngine#20]
When there are more then one location
<img width="1005" alt="screen shot 2018-01-11 at 10 56 11 pm" src="https://user-images.githubusercontent.com/1784705/34844540-e8a4b8f2-f722-11e7-9233-6e9d92f3bbae.png">

Copying the previous month creates an error
![reporthub-error](https://user-images.githubusercontent.com/1784705/34844558-f7f2e5e0-f722-11e7-91aa-9e7a674af339.png)

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-reportHub/pull/34

**Comment by drfaustusfade** [comment]
![2018-01-12_02-34-52](https://user-images.githubusercontent.com/29349472/34849776-35ba9a8a-f741-11e7-9ba0-5496bf07e1f6.gif)

**Comment by drfaustusfade** [comment]
in place of checking condition ===, stock_warehouse_id was reassigned =, so if a report was saved after copying, the first stock_warehouse_id value will be with second etc. To fix report update with corresponding stock_warehouse_id needed.

**Comment by pfitzpaddy** [comment]
Merged on DEV and PROD
