### ISSUE TITLE
Project Focal Point should receive email notifications (along with Target Location Reporting user)

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportEngine#25]
Currently only the Target Location Reporters are sent locations for report OPEN, DUE SOON, DUE TODAY, OVERDUE. It would be great if report [OPEN](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Cluster/Reports/ReportTasksController.js#L214) and report [DUE](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/controllers/Cluster/Reports/ReportTasksController.js#L359) inlcuded the project focal point too!

**Comment by drfaustusfade** [comment]
https://github.com/pfitzpaddy/ngm-reportEngine/pull/27

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD
