### ISSUE TITLE
local.js file name issue

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportEngine#4]
config/local.js has trailing carriage return in name (%0D) that causes git issues on windows machines as it contains disallowed characters for file names. Can we update it?

**Comment by pfitzpaddy** [comment]
This should be in gitignore, not sure how it got into the repo, although it was me. Might have been a commit from the VirtualBox. Anyway the config.js is generated from the server install script 'Dropbox > ngm > ngm-reporthub.server.build.sh' and should not be on github.

**Comment by drfaustusfade** [comment]
Then I propose to delete it from this repo, to keep it clean.

**Comment by pfitzpaddy** [comment]
done
